### ISSUE TITLE
c.LibcloudSpawner.notebook_dir isn't functional

### ISSUE THREAD

**Issue by MRichards99** [tristanlt/jupyter-libcloudspawner#3]
As requested in the Gitter chat, an issue regarding the `notebook_dir` config option when configuring Libcloudspawner.
By default, the notebook server will start in `/tmp`. I would expect to be able to specify a folder in the `jupyterhub_config.py` like you can do with most spawners, something like the following: `c.LibcloudSpawner.notebook_dir = '/folder-name'` - this is what I've tried, with no success. 
I can see in the `jupyterhub-singleuser.service` file (stored at `/etc/systemd/system`) that has a line showing `WorkingDirectory=/tmp`. I would guess it's a case of setting the `WorkingDirectory` variable to what the user sets the `notebook_dir` to be.
Thanks!

**Comment by tristanlt** [comment]
Dear @MRichards99 

Be careful, this modification have an other effect. It remove pinning of server port. If c.Spawner.port isn't set to 8000 ( or other port ) it will randomly set.
